# Generated by Django 4.2.7 on 2025-08-19 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="facultyprofile",
            name="certifications_awards",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="facultyprofile",
            name="degree_certificate",
            field=models.FileField(
                blank=True, null=True, upload_to="faculty_certificates/"
            ),
        ),
        migrations.AddField(
            model_name="facultyprofile",
            name="designation",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="facultyprofile",
            name="educational_qualifications",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="facultyprofile",
            name="subject_expertise",
            field=models.TextField(blank=True, null=True),
        ),
    ]
